name: Fetch Notion and Tweet

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger fetch function
        run: node dist/index.js
