name: Fetch Notion and Tweet

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger fetch function
        run: node dist/index.js
